In [1]:
import pandas as pd

In [2]:
df = pd.read_excel("bought_product.xlsx")

In [3]:
print(df.head())

   age  salary  experience       city  bought_product
0   22   25000           0    Vellore               0
1   24   32000           1    Chennai               1
2   27   40000           3  Bangalore               1
3   30   45000           5  Hyderabad               1
4   35   60000           8    Chennai               1

In [4]:
df.shape

(20, 5)

In [5]:
type(df)

pandas.core.frame.DataFrame

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 5 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   age             20 non-null     int64
 1   salary          20 non-null     int64
 2   experience      20 non-null     int64
 3   city            20 non-null     object
 4   bought_product  20 non-null     int64
dtypes: int64(4), object(1)
memory usage: 932.0+ bytes

In [7]:
# shows how many missing (null/NaN) values are in each column.
df.isnull().sum()

age               0
salary            0
experience        0
city              0
bought_product    0
dtype: int64

In [8]:
# frequency of class labels
# class distribution
df["bought_product"].value_counts()

bought_product
1    14
0     6
Name: count, dtype: int64

In [9]:

df.groupby('city').mean(numeric_only = True)

                 age        salary  experience  bought_product
city
Bangalore  35.666667  62833.333333        9.50        0.666667
Chennai    34.833333  61166.666667        9.00        1.000000
Hyderabad  39.000000  74250.000000       12.75        1.000000
Vellore    24.750000  31750.000000        1.25        0.000000

In [10]:
df.describe()

             age         salary  experience  bought_product
count  20.000000      20.000000   20.000000       20.000000
mean   33.900000   58400.000000    8.350000        0.700000
std     8.168618   23910.799146    6.876926        0.470162
min    22.000000   25000.000000    0.000000        0.000000
25%    27.750000   39500.000000    2.750000        0.000000
50%    33.500000   56500.000000    7.500000        1.000000
75%    38.500000   72500.000000   11.250000        1.000000
max    50.000000  110000.000000   25.000000        1.000000

In [11]:
df.tail(5)

    age  salary  experience       city  bought_product
15   48   95000          20  Bangalore               0
16   50  110000          25  Hyderabad               1
17   23   28000           1    Vellore               0
18   34   58000           8    Chennai               1
19   37   65000          11  Bangalore               1

In [12]:
df.columns

Index(['age', 'salary', 'experience', 'city', 'bought_product'], dtype='object')

In [13]:
df.dtypes

age                int64
salary             int64
experience         int64
city              object
bought_product     int64
dtype: object

In [14]:
# random 5 rows
print(df.sample(5))

    age  salary  experience       city  bought_product
8    45   90000          18    Chennai               1
0    22   25000           0    Vellore               0
17   23   28000           1    Vellore               0
12   33   55000           7  Bangalore               1
11   29   42000           4    Chennai               1

In [15]:
print(df.describe(include='all'))        # stats for all dtypes [web:12][web:15]

              age         salary  experience     city  bought_product
count   20.000000      20.000000   20.000000       20       20.000000
unique        NaN            NaN         NaN        4             NaN
top           NaN            NaN         NaN  Chennai             NaN
freq          NaN            NaN         NaN        6             NaN
mean    33.900000   58400.000000    8.350000      NaN        0.700000
std      8.168618   23910.799146    6.876926      NaN        0.470162
min     22.000000   25000.000000    0.000000      NaN        0.000000
25%     27.750000   39500.000000    2.750000      NaN        0.000000
50%     33.500000   56500.000000    7.500000      NaN        1.000000
75%     38.500000   72500.000000   11.250000      NaN        1.000000
max     50.000000  110000.000000   25.000000      NaN        1.000000

In [16]:
print(df.nunique())                      # unique values per column

age               20
salary            20
experience        17
city               4
bought_product     2
dtype: int64

In [17]:
print(df["city"].unique())               # unique categories in city

['Vellore' 'Chennai' 'Bangalore' 'Hyderabad']

In [18]:
print(df["city"].value_counts(normalize=True))  # class proportions [web:9][web:18]

city
Chennai      0.3
Bangalore    0.3
Vellore      0.2
Hyderabad    0.2
Name: proportion, dtype: float64

In [19]:
print(df.sort_values(by="age").head())   # sort by one column

    age  salary  experience       city  bought_product
0    22   25000           0    Vellore               0
17   23   28000           1    Vellore               0
1    24   32000           1    Chennai               1
10   26   36000           2    Vellore               0
2    27   40000           3  Bangalore               1

In [20]:

print(df["age"].min(), df["age"].max())  # min/max of a feature

22 50

In [21]:

print(df["age"].mean(), df["age"].median())

33.9 33.5

In [22]:

print(df.groupby("city")["salary"].mean())   # mean salary per city

city
Bangalore    62833.333333
Chennai      61166.666667
Hyderabad    74250.000000
Vellore      31750.000000
Name: salary, dtype: float64

In [23]:
print(df.groupby("bought_product").size())   # count per class

bought_product
0     6
1    14
dtype: int64

In [24]:
print(df.rename(columns={"bought_product": "target"}, inplace=False).head())

   age  salary  experience       city  target
0   22   25000           0    Vellore       0
1   24   32000           1    Chennai       1
2   27   40000           3  Bangalore       1
3   30   45000           5  Hyderabad       1
4   35   60000           8    Chennai       1

In [25]:
print(df.drop_duplicates().shape)        # check duplicates

(20, 5)

In [26]:
print(df["age"].between(25, 35).sum())   # count ages in a range

9

In [27]:
print(df[(df["age"] > 30) & (df["bought_product"] == 1)].head())

    age  salary  experience       city  bought_product
4    35   60000           8    Chennai               1
6    31   52000           6  Bangalore               1
7    40   80000          12  Hyderabad               1
8    45   90000          18    Chennai               1
12   33   55000           7  Bangalore               1